"""Actor-domain exports."""

from authsome.actors.identity import (
    IdentityMetadata,
    create_identity,
    current_from_home,
    ensure_local_identity,
    identities_dir,
    identity_exists,
    identity_key_path,
    identity_metadata_path,
    load_identity,
    load_private_key,
    mark_claimed,
    mark_registered,
    public_key_from_did_key,
    public_key_to_did_key,
    remove_legacy_default_identity,
    validate_handle,
)
from authsome.actors.identity_registry import (
    IdentityRegistration,
    IdentityRegistrationError,
    IdentityRegistry,
)
from authsome.actors.proof import (
    POP_AUTH_SCHEME,
    ProofClaims,
    ProofValidationError,
    ReplayCache,
    create_proof_jwt,
    validate_proof_jwt,
)
from authsome.actors.registry import (
    IdentityClaimRecord,
    IdentityClaimRegistry,
    PrincipalRecord,
    PrincipalRegistry,
    PrincipalVaultBindingRecord,
    PrincipalVaultBindingRegistry,
    VaultRecord,
    VaultRegistry,
)

__all__ = [
    "IdentityClaimRecord",
    "IdentityClaimRegistry",
    "IdentityMetadata",
    "IdentityRegistration",
    "IdentityRegistrationError",
    "IdentityRegistry",
    "PrincipalRecord",
    "PrincipalRegistry",
    "PrincipalVaultBindingRecord",
    "PrincipalVaultBindingRegistry",
    "POP_AUTH_SCHEME",
    "ProofClaims",
    "ProofValidationError",
    "ReplayCache",
    "VaultRecord",
    "VaultRegistry",
    "current_from_home",
    "create_identity",
    "create_proof_jwt",
    "ensure_local_identity",
    "identities_dir",
    "identity_exists",
    "identity_key_path",
    "identity_metadata_path",
    "load_identity",
    "load_private_key",
    "mark_claimed",
    "mark_registered",
    "public_key_from_did_key",
    "public_key_to_did_key",
    "remove_legacy_default_identity",
    "validate_proof_jwt",
    "validate_handle",
]
